using System.Diagnostics.Contracts;
using java.lang;
using NPhoenix.Interop;

namespace NPhoenix.Client
{
    /// <summary>
    /// An object that represents a precompiled SQL statement. 
    /// </summary>
    public class PreparedStatement
    {
        private readonly java.lang.Object _statement;

        internal PreparedStatement(java.lang.Object statement)
        {
            Contract.Requires(statement != null);
            _statement = statement;
        }

        /// <summary>
        /// Executes the SQL query in this <see cref="PreparedStatement"/> object and returns the <see cref="ResultSet"/> object generated by the query.
        /// </summary>
        /// <returns></returns>
        public ResultSet ExecuteQuery()
        {
            Object rs = _statement.ExecuteQuery();
            var resultSet = new ResultSet(rs);
            return resultSet;
        }
    }
}